version: "3"

services:
  app:
    build: .
    container_name: routing
    ports:
      - "8001:80"
    volumes:
      - "./:/var/www/html/"
    networks:
      - routing

networks:
  routing:
    driver: bridge